//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDetail
    {
        public int TokenNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public int Age { get; set; }
        public string DateofBirth { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string ConsultingDoctor { get; set; }
        public int TimeSlot { get; set; }
        public int Department { get; set; }
        public string DateofAppointment { get; set; }
        public string Problem { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
    }
}
