//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetail
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public int Department { get; set; }
        public string DoctorName { get; set; }
        public System.DateTime AdmitDate { get; set; }
        public System.DateTime DischargeDate { get; set; }
        public int Service { get; set; }
        public int CostOfTreatment { get; set; }
        public string DoctorCharges { get; set; }
        public string MedicineCharges { get; set; }
        public string RoomCharges { get; set; }
        public int Discount { get; set; }
        public string TotalAmount { get; set; }
        public int Payment { get; set; }
        public string CheckNo { get; set; }
        public int PaymentStatus { get; set; }
        public bool IsActive { get; set; }
    }
}
