//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDetail
    {
        public int DoctorDetailId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int HospitalName { get; set; }
        public string Address { get; set; }
        public int MobileNo { get; set; }
        public int City { get; set; }
        public int State { get; set; }
        public int SpecialistIn { get; set; }
        public int Gender { get; set; }
        public bool IsActive { get; set; }
    }
}
