//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetail
    {
        public int MedicineId { get; set; }
        public string MedicineName { get; set; }
        public int Category { get; set; }
        public string CompanyName { get; set; }
        public string PurchaseDate { get; set; }
        public string Price { get; set; }
        public string ExpiredDate { get; set; }
        public string Stock { get; set; }
        public bool IsActive { get; set; }
    }
}
