//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdmitForm
    {
        public int PatientAdmissionId { get; set; }
        public string DoctorName { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string PlannedProcedure { get; set; }
        public string ItemNumber { get; set; }
        public string PatientName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string GuardianName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string PatientBelow18 { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Contact { get; set; }
        public string State { get; set; }
        public bool IsActive { get; set; }
    }
}
