//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTreatmentDetail
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string MedicineName { get; set; }
        public int Quantity { get; set; }
        public string DosageDesc { get; set; }
        public string Remarks { get; set; }
        public int RoomNumber { get; set; }
        public string RoomType { get; set; }
        public int RoomPrice { get; set; }
        public bool IsActive { get; set; }
    }
}
