//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int PurchaseMedicineId { get; set; }
        public string SupplierName { get; set; }
        public string Code { get; set; }
        public string Date { get; set; }
        public int Category { get; set; }
        public int Medicine { get; set; }
        public string Quantity { get; set; }
        public string Notes { get; set; }
        public string Discount { get; set; }
        public string GrandTotal { get; set; }
        public int Status { get; set; }
        public int Payment { get; set; }
        public bool IsActive { get; set; }
    }
}
